name: dev_mob
description: A new Flutter project.

# Pour publier sur pub.dev, laisse ce champ commenté ou configure-le
# publish_to: 'none' 

environment:
  sdk: '>=3.2.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  async: ^2.11.0

  # Firebase
  firebase_core: ^3.13.0
  firebase_auth: ^5.5.3
  cloud_firestore: ^5.6.7

  # State management
  provider: ^6.1.5

  # Navigation
  go_router: ^15.1.1
  beamer: ^1.7.0 # ⚠️ Attention : évite de combiner go_router + beamer dans le même projet sauf besoin précis

  # UI
  google_fonts: ^6.2.1
  flutter_spinkit: ^5.2.0
  google_sign_in: ^6.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
